# Copyright (C) 2018 Wazuh Inc.
#
# This program is a free software; you can redistribute it
# and/or modify it under the terms of the GNU General Public
# License (version 2) as published by the FSF - Free Software
# Foundation.

# Kibana service

apiVersion: v1
kind: Service
metadata:
  name: kibana
  namespace: wazuh
  labels:
    app: wazuh-kibana
spec:
  selector:
    app: wazuh-kibana
  ports:
    - name: kibana
      port: 5601
      targetPort: 5601
# ---
# apiVersion: extensions/v1beta1
# kind: Ingress
# metadata:
#   name: kibana-ingress-ssl
#   namespace: wazuh
#   annotations:
#     kubernetes.io/ingress.class: azure/application-gateway
#     cert-manager.io/cluster-issuer: letsencrypt-staging
#     cert-manager.io/acme-challenge-type: http01
# #    appgw.ingress.kubernetes.io/backend-path-prefix: "/"
# spec:
#   tls:
#     - hosts:
#       - pci.megatherion.no
#       secretName: kibana-ingress
#   rules:
#   - host: pci.megatherion.no
#     http:
#       paths:
#       - backend:
#           serviceName: wazuh-kibana
#           servicePort: 5601
#         path : /
