kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: gp2-encrypted-retained
provisioner: kubernetes.io/azure-disk
reclaimPolicy: Retain
parameters:
  storageaccounttype: Premium_LRS
  kind: Managed